[package]
name = "rmap"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
colored = "2.1.0"
reqwest = "0.11.23"
sha3 = "0.10.8"
tokio = { version = "1", features = ["full"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
